forum/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'forum'
urlpatterns = [
    # url(r'^$', views.main_page, name='main_page'),
    url(r'^$', views.ForumView.as_view(), name='main_page'),
    url(r'^(?P<category_id>\d+)/category/$', views.CategoryView.as_view(), name='category'),
    url(r'^(?P<sub_id>\d+)/sub_forum/$',
        views.sub_forum, name='sub_forum'),
    url(r'^(?P<thread_id>\d+)/thread/$', views.thread, name='thread'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^registration_success/$', views.registration_success, name='registration_success'),
    url(
        r'^email_confirmation/(?P<user_id>\d+)/(?P<token>[-\w]+)/$',
        views.email_confirmation, name='email_confirmation'
    ),
    url(r'^activation_required/$', views.activation_required, name='activation_required'),
    # url(r'^login/$', views.login, {'template_name': 'forum/login.html'}, name='login'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'forum:main_page'}, name='logout'),
    url(r'^(?P<sub_id>\d+)/new_thread/$', views.new_thread, name='new_thread'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='profile'),
    url(r'^change_profile/$', views.changeprofile, name='change_profile'),
    url(r'^change_avatar/$', views.change_avatar, name='change_avatar'),
    url(r'^change_info/$', views.change_info, name='change_info'),
    url(r'^change_email/$', views.change_email, name='change_email'),
    url(r'^change_password/$', views.password_change, name='change_password'),
    url(r'^password_changed/$', auth_views.password_change_done,
        {
            'template_name': 'forum/profile/password_changed.html',
            'extra_context': {'redirect_to': 'forum:profile'}
        },
        name='password_changed'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>\d+)/edit_thread/$', views.EditThread.as_view(), name='edit_thread'),
    url(r'^(?P<pk>\d+)/edit_post/$', views.EditPost.as_view(), name='edit_post'),
    url(r'^rating/$', views.rating, name='rating'),
]

forum/models.py
from textwrap import shorten

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone

from . import functions
from . import settings as forum_settings
from .templatetags.forum_tags import replace_markdown


class Category(models.Model):
    title = models.CharField(max_length=200)
    precedence = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['precedence']
        verbose_name_plural = 'categories'


class SubForum(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=300, blank=True, null=True, default='')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    precedence = models.IntegerField(default=0)
    create_time = models.DateTimeField(auto_now_add=True)
    # objects = SubForumQuerySet.as_manager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['category__precedence', 'precedence']


class ThreadPostAbstract(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(default=timezone.now)
    full_text = models.TextField()
    raw_text = models.TextField()

    def save(self, *args, **kwargs):
        text_diff = self.text_diff()
        # just_created = self.pk is None
        if text_diff:
            self.raw_text = str(replace_markdown(self.full_text,
                                                 delete=True,
                                                 autoescape=False))
        if text_diff or self.title_diff():
            self.edit_date = timezone.now()
        super(ThreadPostAbstract, self).save(*args, **kwargs)

    def is_edited(self):
        return self.pub_date < self.edit_date

    def text_diff(self):
        try:
            orig = self.__class__.objects.get(pk=self.pk)
        except ObjectDoesNotExist:
            return True
        return self.full_text != orig.full_text

    def title_diff(self):
        return False

    def get_rating(self):
        res = self.users_liked.count() - self.users_disliked.count()
        return res

    def is_liked(self, user):
        query = self.users_liked.filter(id=user.id).exists()
        return query

    def is_disliked(self, user):
        query = self.users_disliked.filter(id=user.id).exists()
        return query

    class Meta:
        abstract = True


class Thread(ThreadPostAbstract):
    thread_title = models.CharField(max_length=70, verbose_name='title')
    subforum = models.ForeignKey(SubForum, on_delete=models.CASCADE)
    is_attached = models.BooleanField(default=False)
    post_add_date = models.DateTimeField(default=timezone.now)
    users_liked = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='threads_liked')
    users_disliked = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='threads_disliked')
    # objects = CustomQuerySet.as_manager()

    def __str__(self):
        return self.thread_title

    def get_absolute_url(self):
        string = '{0}?postid={1}#{1}'
        url = reverse('forum:thread', args=(self.id,))
        return string.format(url, self.id)

    def title_diff(self):
        orig = Thread.objects.get(pk=self.pk)
        return self.thread_title != orig.thread_title

    class Meta:
        ordering = ['-post_add_date', '-pub_date']


class Post(ThreadPostAbstract):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    users_liked = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='posts_liked')
    users_disliked = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='posts_disliked')

    def __str__(self):
        text = shorten(self.full_text, 20, placeholder='...')
        return '%s: %s' % (self.user, text)

    def save(self, *args, **kwargs):
        if self.pk is None:
            thrd_id = self.thread.id
            Thread.objects.filter(id=thrd_id).update(post_add_date=timezone.now())
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        thread_id = self.thread.id
        return '{0}?postid={1}#{1}'.\
            format(reverse('forum:thread', args=(thread_id,)), self.id)


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    signature = models.TextField(default='', max_length=300, blank=True, null=True)
    avatar = models.ImageField(max_length=200, upload_to='avatars', blank=True,
                               null=True)

    new_email = models.EmailField(default='', blank=True, null=True)

    def substitute_mail(self):
        if self.new_email:
            self.user.email = self.new_email
            self.new_email = ''
            self.user.save()
            self.save()

    def save(self, *args, **kwargs):
        if self.avatar:
            if self.pk is not None:
                orig = UserProfile.objects.get(pk=self.pk)
                orig = orig.avatar
            else:
                orig = False
            if orig != self.avatar:
                size = forum_settings.AVATAR_SIZE
                resized_img = functions.resize(size, bytes=self.avatar.read())
                name = self.avatar.name
                orig.delete(save=False)
                file = File(resized_img)
                self.avatar.save(name, file, save=False)
            # check if avatars are compared at all:
            # else:
            #     raise ValueError
        super(UserProfile, self).save(*args, **kwargs)

forum/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import \
    password_validators_help_texts as pswd_help
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _

from . import settings as forum_settings
from .models import Post, SubForum, Thread
from .widgets import ForumWidget

message = _('Username must consist of only lowercase or uppercase letters, numbers, '
            'or _@+.- characters.')
validate_username_chars = RegexValidator(regex=r'^[a-zA-Z0-9_+.@-]+$', message=message)


def validate_username_unique(username):
    try:
        get_user_model().objects.get(username=username)
    except ObjectDoesNotExist:
        return
    else:
        raise ValidationError(_('Username already exists.'), code='exists')


def validate_thread_title_unique(title):
    try:
        Thread.objects.get(thread_title=title)
    except ObjectDoesNotExist:
        return
    else:
        raise ValidationError(_('Thread with that name already exists.'), code='exists')


def validate_avatar(file):
    content_type = file.content_type.split('/')[0]
    if content_type != 'image':
        raise ValidationError(_('File is not an image'), code='wrong_type')
    if file.size > forum_settings.FILE_MAX_SIZE:
        raise ValidationError(_('File size should be less than 1 MB'), code='size_limit')
    return


class AuthenticationFormSub(auth_forms.AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass


class Registration(auth_forms.UserCreationForm):
    username = forms.CharField(max_length=20, min_length=1,
                               label=_('* Username'),
                               help_text=_('Username that will be displayed on forum and'
                                           ' used for authentication.\n'
                                           'May contain 1-20 letters, numbers,'
                                           ' and _@+.- characters'),
                               validators=[
                                   validate_username_chars,
                                   validate_username_unique
                               ])
    email = forms.EmailField(label='* Email')
    password1 = forms.CharField(label=_('* Password'),
                                strip=False,
                                widget=forms.PasswordInput,
                                help_text='\n'.join(pswd_help()))
    password2 = forms.CharField(label=_('* Password confirmation'),
                                widget=forms.PasswordInput,
                                strip=False,
                                help_text=_("Enter the same password as before, for verification."))

    class Meta:
        model = get_user_model()
        fields = [
            'username', 'email', 'password1', 'password2', 'first_name',
            'last_name'
        ]


class NewThread(forms.ModelForm):
    thread_title = forms.CharField(max_length=70, min_length=1, label='Title',
                                   validators=[validate_thread_title_unique])
    full_text = forms.CharField(widget=ForumWidget(attrs={'rows': '12'}), label='Text', min_length=1)
    class Meta:
        model = Thread
        fields = ['thread_title', 'full_text']


class NewThreadEdit(NewThread):
    thread_title = forms.CharField(max_length=70, min_length=1, label='Title')


class Post(forms.ModelForm):
    full_text = forms.CharField(widget=ForumWidget(attrs={'rows': '12'}), label='',
                                min_length=1)

    class Meta:
        model = Post
        fields = ['full_text']


class File(forms.Form):
    upload_file = forms.ImageField(max_length=200, validators=[validate_avatar])


class Info(forms.Form):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    signature = forms.CharField(max_length=500, widget=ForumWidget(attrs={'rows': '12'}), required=False)


class Email(forms.Form):
    new_email = forms.EmailField(help_text='The confirmation mail will be sent to this address.')


# SUBFORUMS_CHOICES = [(sub.id, sub.title) for sub in SubForum.objects.all()]
# SEARCH_BY_CHOICES = [
#     ('pt', 'Posts, threads and titles'),
#     ('p', 'Only posts'),
#     ('t', 'Only thread titles'),
# ]
SORT_BY_CHOICES = [
    ('r', 'Relevance'),
    ('p', 'Publication Date'),
    ('rt', 'Rating')
]

class Search(forms.Form):
    search = forms.CharField(max_length=50, required=False)
    user = forms.CharField(max_length=20, required=False)
    subforums = forms.ModelMultipleChoiceField(required=False,
                                               queryset=SubForum.objects.all(),
                                               help_text=
                                               'Hold "Ctrl" or "Shift" to'
                                               ' select multiple subforums'
                                               ' or to remove selection')
    only_threads = forms.BooleanField(label='Search by first posts only', required=False)
    sort_by = forms.ChoiceField(choices=SORT_BY_CHOICES, initial='r',
                                widget=forms.RadioSelect)

    def clean(self):
        super(Search, self).clean()
        search = self.cleaned_data.get('search')
        user = self.cleaned_data.get('user')
        if not search and not user:
            raise ValidationError(_('Enter either a search string or username.'),
                                  code='empty_search')


class PasswordChange(auth_forms.PasswordChangeForm):
    new_password1 = forms.CharField(label=_("New password"),
                                    widget=forms.PasswordInput,
                                    strip=False,
                                    help_text='\n'.join(pswd_help()))

forum/templates/forum/category.html
{% extends "forum/main_page.html" %}
{% block title %}{{ cat.0.title }}{% endblock %}

forum/templates/forum/edit_post.html
{% extends 'forum/main_page.html' %}
{% block title %}Edit Post{% endblock %}
{% block head %}
{{ form.media }}
{% endblock %}
{% block body %}
<form id="post" class="post" action="" method="post">
        {% csrf_token %}
        {% include 'forum/post_form.html' %}
    <a class="as_input button" href="{{ form.instance.get_absolute_url }}">Cancel</a>
        <input class="excluded" type="submit" value="Save changes"/>
    </form>
{% endblock %}

forum/templates/forum/edit_thread.html
{% extends 'forum/main_page.html' %}
{% block title %}{{ form.instance.thread_title }} | Edit{% endblock %}
{% block head %}
{{ form.media }}
{% endblock %}
{% block body %}
<form class="post" action="" method="post">
    {% csrf_token %}
    {% include 'forum/form.html' %}
    <a class="as_input button" href="{{ form.instance.get_absolute_url }}">Cancel</a>
    <input class="excluded" type="submit" value="Save changes"/>
</form>
{% endblock %}

forum/templates/forum/form.html
{% if form.non_field_errors %}
<ul>
{% for error in form.non_field_errors %}
    <li class="error">
        {{ error }}
    </li>
{% endfor %}
    </ul>
{% endif %}
<ul>
    {% for f in form %}
    {{ f.label_tag }}
    {% for error in f.errors %}
    <li class="error">
        {{ error }}
    </li>
    {% endfor %}
    <li>
        {{ f }}
        {% if f.help_text %}
        <p class="helptext">{{ f.help_text|linebreaksbr }}</p>
        {% endif %}
    </li>
    {% endfor %}
</ul>

forum/templates/forum/login.html
{% extends "forum/main_page.html" %}
{% block title %}Log in{% endblock %}
{% block body %}
<form action="{% url 'forum:login' %}?next={{ next }}" method="post">
    {% csrf_token %}
    {% include 'forum/form.html' %}
    <input class="excluded" type="submit" value="Log in"/>
</form>
{% endblock %}

forum/templates/forum/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'main_page.css' %}"/>

    <title>{% block title %}My forum{% endblock %} </title>
    <meta charset="UTF-8"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="{% static 'csrf_cookie.js' %}"></script>
    <script src="{% static 'messages.js' %}"></script>
    {% block head %}
    {% load forum_tags %}
    {% endblock %}
</head>
<body>
<div class="header">
    <ul class="options">
    {% if not request.user.is_authenticated %}
        <li id="signup">
            <a class="button" href="{% url 'forum:sign_up' %}?next={{ request.path }}">Sign up</a>
        </li>
        <li id="login">
            <a class="button" href="{% url 'forum:login' %}?next={{ request.path }}">Sign in</a>
        </li>
    {% else %}
        <li id="logout">
            <a class="button" href="{% url 'forum:logout' %}?next={{ request.path }}">Log out</a>
        </li>
        <li id="profile">
            {% comment %}
            {% if request.user.userprofile.avatar %}
            <img src="{{ request.user.userprofile.avatar.url }}" width="45px" height="45px"/>
            {% else %}
            <img src="{% static 'avatar.jpg' %}" width="45px" height="45px"/>
            {% endif %}
            {% endcomment %}
            <a class="button" href="{% url 'forum:profile' %}">{{ request.user.username }}</a>
        </li>
        {% endif %}
        <li id="search">
            <a class="button" href="{% url 'forum:search' %}">Search</a>
        </li>
    </ul>
</div>
<p class="history">
    <a href="{% url 'forum:main_page' %}">Main page</a>{% block links %}{% endblock %}
</p>
{% block body %}
{% for c in cat %}
    <ul class="subforum">
    <li class="header"><a href="{% url 'forum:category' c.id %}">{{ c.title }}</a></li>
    {% if c.subforum_set.all %}
        {% for s in sub %}
        {% if s.category == c %}
        <li class="subforum">
                <div class="subforum">
                    <p class="subtitle">
                        <a href="{% url 'forum:sub_forum' s.id %}?page=1">{{ s.title }}</a>
                        <br/>
                        <span class="subdescr">{{ s.description }}</span>
                    </p>
                </div>
            {% get_subforum_info s as sub_info %}
                <div class="stats">
                    <p>Threads: {{ sub_info.threads_num }}<br/>Posts: {{ sub_info.posts_num }}</p>
                </div>
                {% if sub_info.last_thread %}
                <div class="lastthread">
                    {% if sub_info.last_post.user.userprofile.avatar %}
                    <img src={{ sub_info.last_post.user.userprofile.avatar.url }} width="45px" height="45px"/>
                    {% else %}
                    <img src="{% static 'avatar.jpg' %}" width="45px" height="45px"/>
                    {% endif %}
                    <p class="lastthread">
                        <a href="{% url 'forum:thread' sub_info.last_thread.id %}?page=1">
                            {{ sub_info.last_thread.thread_title|truncatechars:15 }}
                        </a>
                        <br/>
                        by <a class="secondary" href="{% url 'forum:profile' sub_info.last_post.user.id %}">
                            {{ sub_info.last_post.user.username|truncatechars:14 }}
                        </a><br/>
                        {{ sub_info.last_post.pub_date|date:"N j, Y, H:i" }}
                    </p>
                </div>
                {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ul>
    {% endif %}
{% endfor %}
{% endblock %}
</body>
</html>

forum/templates/forum/messages.html
{% if messages %}
            {% for message in messages %}
<p class="{{ message.tags }}">{{ message }}<a href="#" class="close">✖</a></p>
{% endfor %}
            {% endif %}

forum/templates/forum/new_thread.html
{% extends 'forum/main_page.html' %}
{% block title %}Create new thread{% endblock %}
{% block head %}
{{ form.media }}
{% endblock %}
{% block body %}
<form class="post" action="{% url 'forum:new_thread' sub_id %}" method="post">
    {% csrf_token %}
    {% include 'forum/form.html' %}
    <input class="excluded" type="submit" value="Create thread"/>
</form>
{% endblock %}

forum/templates/forum/paginator.html
<div id="pagebar">
    {% if 1 not in pages_list %}
    <a class="button" href="?page=1">First</a>
    {% endif %}
    {% for n in pages_list %}
    {% if num_page != n %}
    <a class="button" href="?page={{ n }}">{{ n }}</a>
    {% else %}
    <span class="page">{{ n }}</span>
    {% endif %}
    {% endfor %}
    {% if last_page not in pages_list %}
    <a class="button" href="?page={{ last_page }}">Last ({{ last_page }})</a>
    {% endif %}
</div>

forum/templates/forum/rating_form.html
<div class="rating-bar">
{% with users_liked=instance.users_liked.all %}
<button class="like {% if request.user in users_liked %}liked{% endif %}"
        data-id="{{ id }}" data-obj="{{ obj }}" data-action="like">+</button>
{% endwith %}
<span>{{ instance.get_rating }}</span>
{% with users_disliked=instance.users_disliked.all %}
<button class="dislike {% if request.user in users_disliked %}disliked{% endif %}"
        data-id="{{ id }}" data-obj="{{ obj }}" data-action="dislike">-</button>
{% endwith %}
    </div>

forum/templates/forum/search_form.html
{% extends 'forum/main_page.html' %}
{% block title %}Search{% endblock %}
{% block links %}{% endblock %}
{% block head %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'sub_forum.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'thread.css' %}"/>

{% endblock %}
{% block body %}
<form action="{% url 'forum:search' %}" method="get">
    {% include 'forum/form.html' %}
    <input class="excluded" type="submit" value="Search"/>
</form>
{% if query %}
<script>
    $(document).ready(function() {
    $('html, body').animate({
        scrollTop: $(".unattached").offset().top
    }, 1000);
    });
</script>
<ul class="unattached">
    <li class="h3">{{ num_res }} result{{ num_res|pluralize }} were found</li>
    {% for data in query %}
    {% with data.object as data %}
    <li class="thread ">
<p class="secondary">
    {{ data.pub_date|date:"N j, Y, H:i" }}
    {% comment %}
    by
    <a href="{% url 'forum:profile' data.user.id%}" class="secondary">{{ data.user.username }}</a>
    {% endcomment %}
</p>
        {% if data.thread %}
<a href="{{ data.get_absolute_url }}">{{ data.thread.thread_title }}</a>
        {% else %}
        <a href="{{ data.get_absolute_url }}">{{ data.thread_title }}</a>
        {% endif %}
<p class="search-text">{{ data.raw_text|truncatewords:100|linebreaksbr }}</p>
        </li>
    {% endwith %}
    {% endfor %}
</ul>
{% elif num_res == 0 %}
    <p class="center">No results were found</p>

{% endif %}
{% if query %}
<div id="pagebar">
    {% if 1 not in pages_list %}
    <a class="button" href="?page=1&{{ get }}">First</a>
    {% endif %}
    {% for n in pages_list %}
    {% if num_page != n %}
    <a class="button" href="?page={{ n }}&{{ get }}">{{ n }}</a>
    {% else %}
    <span class="page">{{ n }}</span>
    {% endif %}
    {% endfor %}
    {% if last_page not in pages_list %}
    <a class="button" href="?page={{ last_page }}&{{ get }}">Last ({{ last_page }})</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}

forum/templates/forum/sub_forum.html
{% extends "forum/main_page.html" %}
{% block title %}{{ sub.title }}{% endblock %}
{% block head %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'sub_forum.css'%}"/>
{% endblock %}
{% block links %}
/<a href="{% url 'forum:category' sub.category.id %}">{{ sub.category.title }}</a>
{% endblock %}
{% block body %}
<div id="body">
    <h1>{{ sub.title }}</h1>
    {% if request.user.is_authenticated %}
    <div id="add"><a class="button" href="{% url 'forum:new_thread' sub.id %}">New thread</a></div>
    {% endif %}
    {% if attach_threads %}
    <ul class="attached">
    <li class="h3">Attached</li>
        {% include 'forum/threadlist.html' with threads=attach_threads %}
    </ul>
    {% endif %}
    <ul class="unattached">
    <li class="h3">
        Threads
    </li>
        {% if threads.exists %}
        {% include 'forum/threadlist.html' with threads=threads %}
        {% else %}
        <li class="thread">There is no threads yet</li>
        {% endif %}
    </ul>
</div>
{% include 'forum/paginator.html' %}
{% endblock %}

forum/templates/forum/thread.html
{% extends "forum/main_page.html" %}
{% load staticfiles %}
{% load forum_tags %}
{% block title %}{{ thread.thread_title }}{% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'sub_forum.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'thread.css' %}"/>
<script>
$(document).ready(function() {
$('.rating-bar').on('click', 'button', function(event){
var button, action;
button = $(this);
action = button.attr('data-action');
$.ajax({
url: '{% url 'forum:rating' %}',
data: {
action: button.attr('data-action'),
id: button.attr('data-id'),
object: button.attr('data-obj'),
csrfmiddlewaretoken: csrftoken
},
type: 'POST',
dataType: 'json'
}).done(function(json) {
if (json.status === 'ok') {
var mapObj = {
'like': 'liked',
'dislike': 'disliked'
};
button.toggleClass(mapObj[action]);
button.parent().children('span').html(json.count);
}
});

event.preventDefault();
});
});
</script>
<script src="{% static 'rating.js' %}"></script>
<script src="{% static 'spoiler.js' %}"></script>
{{ form.media }}
{% endblock %}
{% block links %}
{% with thread.subforum as subforum %}
/<a href="{% url 'forum:category' subforum.category.id %}">{{ subforum.category.title }}</a>/
<a href="{% url 'forum:sub_forum' subforum.id %}?page=1">{{ subforum.title }}</a>
{% endwith %}
{% endblock %}
{% block body %}
<div id="body">
    <h1>{{ thread.thread_title }}</h1>
    <ul class="unattached">
        {% for p in posts %}
        <li class="thread">
            <div class="profile">
                {% with p.user.userprofile.avatar as user_avatar %}
                {% if user_avatar %}
                <img src="{{user_avatar.url }}" alt="Avatar"/>
                {% else %}
                <img src="{% static 'avatar.jpg' %}" alt="Avatar"/>
                {% endif %}
                {% endwith %}
                <br/>
                <a class="nick" href="{% url 'forum:profile' p.user.id %}">{{ p.user.username }}</a><br/>
                <a class="messages" href="{% url 'forum:search' %}?user={{ p.user.username }}&search_by=pt&sort_by=p">
                    Messages: {{ p.user.post_set.count|add:p.user.thread_set.count }}</a>
            </div>
            <div class="message">
                <span class="date" id="{{ p.id }}">
                    <a href="#{{ p.id }}">{{ p.pub_date|date:"N j, Y, H:i" }}</a>
                </span>
                {% if request.user.is_authenticated %}
                {% if p.thread_title %}
                {% include 'forum/rating_form.html' with obj='thread' id=p.id instance=p %}
                {% else %}
                {% include 'forum/rating_form.html' with obj='post' id=p.id instance=p %}
                {% endif %}
                {% endif %}
                <br/>
                <div class="text">{{ p.full_text|replace_markdown|linebreaksbr }}</div>
                {% with signature=p.user.userprofile.signature %}
                {% if signature %}
                <div class="sign">{{ signature|replace_markdown|linebreaksbr }}</div>
                {% endif %}
                {% endwith %}
            </div>
            {% if p.user.id == request.user.id %}
            <div class="m_options">
                {% if p.thread_title %}
                <a class="edit button" href="{% url 'forum:edit_thread' p.id %}">Edit</a>
                {% else %}
                <a class="edit button" href="{% url 'forum:edit_post' p.id %}">Edit</a>
                {% endif %}
                    </div>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% if request.user.is_authenticated and request.user.is_active %}
    <form id="post" class="post" action="{% url 'forum:thread' thread.id %}" method="post">
        {% csrf_token %}
        {% include 'forum/post_form.html' %}
        <input class="excluded" type="submit" value="Submit"/>
    </form>
    {% endif %}
</div>
{% include 'forum/paginator.html' %}
{% endblock %}