forum/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'forum'
urlpatterns = [
    # url(r'^$', views.main_page, name='main_page'),
    url(r'^$', views.ForumView.as_view(), name='main_page'),
    url(r'^(?P<category_id>\d+)/category/$', views.CategoryView.as_view(), name='category'),
    url(r'^(?P<sub_id>\d+)/sub_forum/$',
        views.sub_forum, name='sub_forum'),
    url(r'^(?P<thread_id>\d+)/thread/$', views.thread, name='thread'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^registration_success/$', views.registration_success, name='registration_success'),
    url(
        r'^email_confirmation/(?P<user_id>\d+)/(?P<token>[-\w]+)/$',
        views.email_confirmation, name='email_confirmation'
    ),
    url(r'^activation_required/$', views.activation_required, name='activation_required'),
    # url(r'^login/$', views.login, {'template_name': 'forum/login.html'}, name='login'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'forum:main_page'}, name='logout'),
    url(r'^(?P<sub_id>\d+)/new_thread/$', views.new_thread, name='new_thread'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='profile'),
    url(r'^change_profile/$', views.changeprofile, name='change_profile'),
    url(r'^change_avatar/$', views.change_avatar, name='change_avatar'),
    url(r'^change_info/$', views.change_info, name='change_info'),
    url(r'^change_email/$', views.change_email, name='change_email'),
    url(r'^change_password/$', views.password_change, name='change_password'),
    url(r'^password_changed/$', auth_views.password_change_done,
        {
            'template_name': 'forum/profile/password_changed.html',
            'extra_context': {'redirect_to': 'forum:profile'}
        },
        name='password_changed'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>\d+)/edit_thread/$', views.EditThread.as_view(), name='edit_thread'),
    url(r'^(?P<pk>\d+)/edit_post/$', views.EditPost.as_view(), name='edit_post'),
    url(r'^rating/$', views.rating, name='rating'),
]

forum/templates/forum/profile/change_avatar.html
{% extends 'forum/profile/profile.html' %}
{% block title %}{{ user.username }} | Change avatar{% endblock %}
{% block info %}
<form enctype="multipart/form-data" action="{% url 'forum:change_avatar' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
        {{ form.upload_file.errors }}
        {{ form.upload_file.label_tag }}<br/>
    {{ form.upload_file }}<br/>
    <input class="excluded" type="submit" value="Upload"/>
</form>

{% endblock %}

forum/templates/forum/profile/change_email.html
{% extends 'forum/profile/profile.html' %}
{% block title %}{{ user.username }} | Change Email{% endblock %}
{% block info %}
<p>Current Email: {{ user.email }}</p>
<form action="{% url 'forum:change_email' %}" method="post">
    {% csrf_token %}
    {% include 'forum/form.html' %}
    <input class="excluded" type="submit" value="Confirm"/>
</form>
{% endblock %}

forum/templates/forum/profile/change_email_message.html
Dear {{ username }},
To validate your new email, you need to follow the link below:
{{ link }}

forum/templates/forum/profile/change_info.html
{% extends 'forum/profile/profile.html' %}
{% block title %}{{ user.username }} | Change information{% endblock %}
{% block info %}
<form action="{% url 'forum:change_info' %}" method="post">
    {% csrf_token %}
        {% include 'forum/form.html' %}
        <input class="excluded" type="submit" value="Confirm"/>
</form>

{% endblock %}

forum/templates/forum/profile/change_password.html
{% extends 'forum/profile/profile.html' %}
{% block title %}{{ request.user.username }} | Change password{% endblock %}
{% block info %}
<form action="{% url 'forum:change_password' %}" method="post">
    {% csrf_token %}
        {% include 'forum/form.html' %}
        <input class="excluded" type="submit" value="Save changes"/>
</form>

{% endblock %}

forum/templates/forum/profile/change_profile.html
{% extends "forum/profile/profile.html" %}
{% block title %}{{ user.username }} | Change Profile{% endblock %}


{% block info %}{% endblock %}

forum/templates/forum/profile/password_changed.html
{% extends 'forum/main_page.html' %}
{% block title %}Password Changed{% endblock %}
{% block body %}
<p>{{ request.user.username }}, your password has been changed.</p>
<a href="{% url redirect_to %}">Please click on this link or wait for automatic redirection</a>
{% endblock %}

forum/templates/forum/profile/profile.html
{% extends 'forum/main_page.html' %}
{% block title %}{{ user.username }} | Profile{% endblock %}
{% block head %}
{% load staticfiles %}
{% load forum_tags %}
<link rel="stylesheet" type="text/css" href="{% static 'sub_forum.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}"/>
<script src="{% static 'spoiler.js' %}"></script>
<script>
    $(document).ready(function() {
    if ($('form').length) {
    $('html, body').animate({
        scrollTop: $("form").offset().top
    }, 0);
    }
    });
</script>
{{ form.media }}
{% endblock %}
{% block body %}
<div class="content">
    {% include 'forum/messages.html' %}
    <ul class="subforum">
        <li>
            {% if user_profile.avatar %}
            <img src="{{ user_profile.avatar.url }}"/>
            {% else %}
            <img src="{% static 'avatar.jpg' %}"/>
            {% endif %}
            <h2>Username: {{ user.username }}</h2>
            {% if request.user.id == user.id %}
            <p>Email: {{ user.email }}</p>
            {% if email_confirm %}
            {% include 'forum/registration/confirmation_form.html' with url='forum:profile' %}
            {% endif %}
        </li>
        <li>
            <div class="menu">
                <a class="button" href="{% url 'forum:change_info' %}">Change information</a>
                <a class="button" href="{% url 'forum:change_avatar' %}">Change avatar</a>
                <a class="button" href="{% url 'forum:change_email' %}">Change email</a>
                <a class="button" href="{% url 'forum:change_password' %}">Change password</a>
            </div>
        </li>
        {% endif %}
        </ul>
        {% block info %}
    <ul class="subforum">
        <li class="info">
            <h3>User information:</h3>
            <p>First name: {{ user.first_name }}</p>
            <p>Last name: {{ user.last_name }}</p>
            <div class="text">Signature: {{ user_profile.signature|replace_markdown }}</div>
        </li>
        <li class="stats">
            <h3>User statistics:</h3>
            <p>Registration date: {{ user.date_joined }}</p>
            <p>Last login: {{ user.last_login }}</p>
            <ul class="threads">
            <li class="header"><a href="{% url 'forum:search' %}?user={{ user }}&sort_by=p&search_by=t">Threads ({{ thread_count }})</a></li>
                {% for t in last_threads %}
                <li>
                    <a href="{% url 'forum:thread' t.id %}?page=1">{{ t.thread_title }}</a>
                </li>
                {% endfor %}
            </ul>
            <ul class="threads">
            <li class="header"><a href="{% url 'forum:search' %}?user={{ user }}&sort_by=p&search_by=p">Posts ({{ post_count }})</a></li>
                {% for p in last_posts %}
                <li>
                    <a href="{{ p.get_absolute_url }}">{{ p.thread.thread_title }}</a>
                </li>
                {% endfor %}
            </ul>
        </li>
    </ul>
    {% endblock info %}
</div>
{% endblock %}